### ISSUE TITLE
Feature: Add Location Settings PopUp When user Click on Sport

### ISSUE THREAD

**Issue by vikasdesale** [mnarasimhan02/WeSport#1]
**Subject:** Add new functionality.

**New Functionality Description:**
When the user clicks on sport then new popup dialog should be open to on the location.
this is great if we add this to the app instead message "Turn on Location settings"

**Existing One:**
   it only displays a message "Turn on Location settings"

Nice App @mnarasimhan02

**Comment by mnarasimhan02** [comment]
This is fixed in 2.0 and and app is available on App Store
