### ISSUE TITLE
Feature Change: Remove next from Main Activity Action bar to easy use of user

### ISSUE THREAD

**Issue by vikasdesale** [mnarasimhan02/WeSport#2]
**Subject:** Doesn't Need Next on Main Activity Action bar.

In application when the individual sport is selected every time the user needs to click on next button on the action bar.
so for easy to use to user remove next button from the main activity.

**New Change:**
remove the next button from the main activity action bar

**Add:** 
On user Click on the individual sports launch Map Activity instead, of user need to select next.

👍 😄

**Comment by mnarasimhan02** [comment]
This is fixed in V2.0. App available in app store
