### ISSUE TITLE
Feature Change: Add Menu on Main Activity.

### ISSUE THREAD

**Issue by vikasdesale** [mnarasimhan02/WeSport#3]
**Subject:**  Add menu on Main Activity.

**Existing One:**
In application when the user long clicks on location then it opens next activity for the game and then menus singout and existing created games.
it is not easy to use to the user. also after the relaunch of application.
for next time when the user wants to see created games, again user need to long click to see history or past games created. 

**New Change:**
Add menu on Main Activity Add menus
1.View All games: Launch Activity which displays All created sport except  "Add a Game"  feature(Remove Floating point Action Button Dynamically if Activity launches from Main Activity else display button when user long click on a location to add a game.) because user going from the main activity.
2.Deleted All games
3.Signout

👍 😄

**Comment by mnarasimhan02** [comment]
Hi Vikas
Exactly for the above reason, the widget was created, if you add the widget, you can click on the Wepsort icon from the widget and that will take you to the summary page where you can see all games . This avoids the user by navigating in sequence to the correct page.
Thanks, Mahesh
