### ISSUE TITLE
New Feature: Add Help Menu 

### ISSUE THREAD

**Issue by vikasdesale** [mnarasimhan02/WeSport#4]
**New Feature:**
Add help menu.

**Reason:**
because on first-time use I can't easily found all features like create the game by long clicking on Location marker.

👍 😄

**Comment by mnarasimhan02** [comment]
Hi Vikas
There is an Introactivity (appears on first time install) that provides complete details of the app, various screens and its functionality and more over, on each screen navigation, there is a snackbar (example: once you get into Mapsactivity, user would be prompted to either long click or type the address) and hence I don't think this is required feature now and hence closing this

Thanks, Mahesh

**Comment by vikasdesale** [comment]
Hi Mahesh
   I checked out once again, snack bar will work fine after loading google maps.
   Thank you for the response.

You're Welcome!
Vikas
